version: "3.8"

services:

  mynode:
    build:
      context: .
      dockerfile: mynode.dockerfile
    ports:
      - "3000:3000"
    networks:
      - mynodeapp-network
  mongodb:
    image: mongo
    networks:
      - mynodeapp-network
    volumes:
      - db_data:/data/db

networks:
  mynodeapp-network
    driver: bridge

volumes:
  db_data: