version: "3.8"

services:
  drupal:
    image: drupal
    ports:
      - "9090:80"
    volumes:
      - ./modules:/var/www/html/modules
      - ./profiles:/var/www/html/profiles
      - ./themes:/var/www/htlm/themes
      - /var/www/html/sites
    restart: always
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    volumes:
      - ./postgress-data:/var/lib/postgresql/data
    secrets:
     - db_password
    restart: always

secrets:
  db_password:
    file: db_password.txt